/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2016-05-16 07:09:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class frmRegistroSintoma_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link href=\"Plantilla/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"Plantilla/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"Plantilla/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/masterHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"content-wrapper\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t             <div class=\"panel-heading\">\r\n");
      out.write("\t               COMPLETAR DATOS\r\n");
      out.write("\t             </div>\r\n");
      out.write("\t              <div class=\"row\">\r\n");
      out.write("\t\t             <div class=\"panel-body\">\r\n");
      out.write("\t\t             \t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t  <form>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">Enfermedad/Predecesor</label>\r\n");
      out.write("\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" placeholder=\"Enfermedad\">\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputPassword1\">Síntomas</label>\r\n");
      out.write("\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" placeholder=\"Síntomas\">\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">Probabilidad que no se de el predecesor</label>\r\n");
      out.write("\t\t\t\t\t\t    <input class=\"form-control\" placeholder=\"Probabilidad\">\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t  \t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">Probabilidad que se de el predecesor</label>\r\n");
      out.write("\t\t\t\t\t\t    <input class=\"form-control\" placeholder=\"Probabilidad\">\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t\t  <button class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("                              Agregar\r\n");
      out.write("                            </button>\r\n");
      out.write("\t\t\t\t\t\t </form>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t         \r\n");
      out.write("\t         <div class=\"panel panel-default\">\r\n");
      out.write("\t             <div class=\"panel-heading\">\r\n");
      out.write("\t               LISTA DE SINTOMAS\r\n");
      out.write("\t             </div>\r\n");
      out.write("\t              <div class=\"row\">\r\n");
      out.write("\t\t             <div class=\"panel-body\">\r\n");
      out.write("\t\t              <div class=\"col-md-10\">\r\n");
      out.write("\t\t             \t<div class=\"table-responsive\">\r\n");
      out.write("                                <table class=\"table table-striped table-bordered table-hover\">\r\n");
      out.write("                                    <thead style=\"background: grey\">\r\n");
      out.write("                                        <tr>\r\n");
      out.write("                                            <th>SINTOMA</th>\r\n");
      out.write("                                            <th>PROBABILIDAD (SÍ)</th>\r\n");
      out.write("                                            <th>PROBABILIDAD (NO)</th>\r\n");
      out.write("                                        </tr>\r\n");
      out.write("                                    </thead>\r\n");
      out.write("                                    <tbody>\r\n");
      out.write("                                        \r\n");
      out.write("                                    </tbody>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </div>\r\n");
      out.write("                         </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t         <button class=\"btn btn-primary btn-lg\" data-toggle=\"modal\" data-target=\"#myModal\">\r\n");
      out.write("                              GUARDAR\r\n");
      out.write("                            </button>\r\n");
      out.write("\t      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/masterFooter.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"Plantilla/js/jquery-1.11.1.js\"></script>\r\n");
      out.write("    <script src=\"Plantilla/js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
