/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2016-07-05 02:33:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class frmCuestionario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\t<link href=\"Plantilla/css/bootstrap.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"Plantilla/css/font-awesome.css\" rel=\"stylesheet\" />\r\n");
      out.write("    <link href=\"Plantilla/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/masterHeader.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<form method=\"post\" action=\"sCuestionario\">\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- MENU SECTION END-->\r\n");
      out.write("    <div class=\"content-wrapper\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("                    <h4 class=\"page-head-line\">TEST DE DIAGNOSTICO DEL DENGUE !! </h4>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>                \r\n");
      out.write("                    <div class=\"panel panel-default\">\r\n");
      out.write("                    <div class=\"panel-heading\">\r\n");
      out.write("                        RESPONDER LAS SIGUIENTES PREGUNTAS\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                    <div class=\"panel-body\">\r\n");
      out.write("                     \r\n");
      out.write("                     \t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">¿Tiene dolor muscular?</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion1DM\" id=\"optionsRadios1\" value=\"D_muscular\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    SÍ\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion1DM\" id=\"optionsRadios2\" value=\"~D_muscular\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    NO\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">¿Tiene dolor de cabeza?</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion2DC\" id=\"opcion2DC\" value=\"D_cabeza\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    SÍ\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion2DC\" id=\"opcion2DC1\" value=\"~D_cabeza\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    NO\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">¿Tiene dolor articular?</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion3DA\" id=\"opcion3DA\" value=\"D_articular\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    SÍ\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion3DA\" id=\"opcion3DA1\" value=\"~D_articular\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    NO\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t</div>     \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t <div class=\"col-md-6\">\r\n");
      out.write("\t                     \r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">¿Tiene vómito?</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion4V\" id=\"opcion4V\" value=\"Vomito\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    SÍ\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion4V\" id=\"opcion4V1\" value=\"~Vomito\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    NO\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">¿Tiene fiebre?</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion5F\" id=\"optionsRadios1\" value=\"Fiebre\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    SÍ\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion5F\" id=\"optionsRadios2\" value=\"~Fiebre\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    NO\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">¿Tiene náuseas?</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion6N\" id=\"optionsRadios1\" value=\"Nauseas\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t    SÍ\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"radio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <label>\r\n");
      out.write("\t\t\t\t\t\t\t\t    <input type=\"radio\" name=\"opcion6N\" id=\"optionsRadios2\" value=\"~Nauseas\">\r\n");
      out.write("\t\t\t\t\t\t\t\t    NO\r\n");
      out.write("\t\t\t\t\t\t\t\t  </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t </div> \t\t\t\t\t           \r\n");
      out.write("                       \r\n");
      out.write("                     </div> \r\n");
      out.write("                     </div>  \r\n");
      out.write("                                        \r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary btn-lg\" name=\"btnDiagnosticar\" value=\"DIAGNOSTICAR\" >\r\n");
      out.write("                              DIAGNOSTICAR\r\n");
      out.write("                            </button> \r\n");
      out.write("                            \r\n");
      out.write("                    </div>  \r\n");
      out.write("               </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/masterFooter.jsp", out, false);
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"Plantilla/js/jquery-1.11.1.js\"></script>\r\n");
      out.write("    <script src=\"Plantilla/js/bootstrap.js\"></script>\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
